2024-12-19 17:47:15,908 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF0FB310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:15,935 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 17:47:15,936 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 17:47:16,034 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 17:47:16,083 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 17:47:16,095 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 17:47:16,111 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF110A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:16,513 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF477550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:16,515 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274A46529A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:16,716 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF110940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:17,117 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF110070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:17,119 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274A4658DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:17,320 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF071670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 17:47:17,721 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000274AF071F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:10,263 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C09C520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:10,291 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:09:10,295 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:09:10,380 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:09:10,429 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:09:10,467 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C0B8670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:10,471 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:09:10,869 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C059460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:10,871 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C059B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:11,072 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C064700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:11,473 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C0646D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:11,475 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C09CD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:11,676 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C09CC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:09:12,078 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5C09C610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:29,401 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F42F6280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:29,432 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:25:29,435 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:25:29,542 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:25:29,591 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:25:29,596 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:25:29,606 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F432A310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,008 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F430E4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,010 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F430EF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,211 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F430E6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,612 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F42F64C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,614 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F432A610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:30,815 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F432A130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:25:31,217 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F5F42C29A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:23,785 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7887107C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:23,816 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:46:23,826 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:46:23,900 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:46:23,905 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:46:23,959 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:46:23,990 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E78873D370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:24,392 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E788747070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:24,394 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7882F2E20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:24,595 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7882F2490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:24,997 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7887479A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:24,999 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E788747C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:25,200 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E788747A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:46:25,601 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E788710310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:07,975 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6296715E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:08,009 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:50:08,012 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:50:08,150 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:50:08,159 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:50:08,163 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:50:08,181 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6296970A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:08,582 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A629260970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:08,584 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A629671400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:08,784 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A629671850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:09,185 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A61E85CDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:09,187 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A629253C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:09,389 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A629253EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:50:09,791 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6292531C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:12,630 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145AE753BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:12,660 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:51:12,662 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:51:12,765 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:51:12,777 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:51:12,825 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 18:51:12,836 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145AE75BCA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:13,238 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145ABAF2280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:13,240 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145A3C6CE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:13,442 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145A3C6CCD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:13,842 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145ABAF9BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:13,844 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145ABB1CBE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:14,045 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145ABB03670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 18:51:14,447 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145ABB035B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:39,308 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C586E130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:39,339 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 19:42:39,342 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 19:42:39,438 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 19:42:39,482 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 19:42:39,484 - WARNING - Connection pool is full, discarding connection: sitweb.22889.club. Connection pool size: 10
2024-12-19 19:42:39,511 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C54F0310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:39,912 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C58A2BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:39,914 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C54CFC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:40,115 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C587BE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:40,516 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C54F0FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:40,518 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174BAA2EEE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:40,719 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C58A22E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 19:42:41,120 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174C58A2640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
